check:
  - thoth-build
build:
  base-image: "registry.access.redhat.com/ubi8/nodejs-12"
  build-stratergy: Source
  registry: quay.io
  registry-org: aicoe
  registry-project: operate-first-app
  registry-secret: aicoe-pusher-secret
